// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icfdrrmmacnmdpnwimya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljZmRycm1tYWNubWRwbndpbXlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjI2ODksImV4cCI6MjA2MjU5ODY4OX0.LMOMAMB69cSSkPB9XO_1UnDnQqQ47FFMM5fD8po16Hc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);